#
# This task configures the hosts with two LVM volume groups.
#
# Host in maas inventory must define two variables:
#
# device_ssd - A block device to setup the SSD pool with 
# device_hdd - A block device to setup the DISK pool with 
#
# This role will create the following LVM layout:
#
# /dev/vg-ssd - Volume group with SSD space
# /dev/vg-disk - Volume group with HDD space
#

- name: Create the SSD volume group. 
  become: yes
  lvg:
    vg: vg-ssd
    pvs: "{{ device_ssd }}"

- name: Create the DISK volume group. 
  become: yes
  lvg:
    vg: vg-disk
    pvs: "{{ device_hdd }}"

- name: Install tools for thin provisioning
  become: yes
  package:
    name:
      - thin-provisioning-tools
    state: latest
    