---
# 2021 owner: Lili
# Playbook for the Supermicro-2 Machine
#
# This machine is deployed by MAAS and hosts the jupyter container
#

- hosts: supermicro-2
  name: Apply networking configuration
  remote_user: ubuntu
  roles:
    - netplan 

- hosts: supermicro-2
  name: Apply disk layout and install LXD
  remote_user: ubuntu
  roles:
    - lvm
    - lxd
#
#- hosts: supermicro-2
#  name: Setup supermicro-2 to serve jupyter hub.
#  tags:
#    - jupyter
#  roles:
#    - jupyter
