# -*- mode: ruby -*-
# vi: set ft=ruby :

# Test playbooks using a VM

require 'pathname'

num_disks = 2
playbook = 'vagrant.yaml'
box = "ubuntu/bionic64"
cpus = "4" 
memory = "8192" 
disksize = 64*1024 

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_check_update = false
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.50.4",
    virtualbox__intnet: true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    for i in 0..num_disks-1
      disk = 'extra' + i.to_s + '.vdi'
      unless File.exist?(disk)
        vb.customize ['createmedium', '--filename', disk, '--variant', 'Standard', '--size', disksize * 2]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 2 + i, '--device', 0, '--type', 'hdd', '--medium', disk]
    end

    vb.memory = memory
    vb.cpus = cpus

  end

  # Check to see if the playbook is available. 
  if File.exist?(playbook)
    # Run Ansible from the Vagrant VM
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = playbook
    end
  end

end
